server:
  port: 80
  
spring:
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:./file/
    - file:F:/迅雷下载/
  media: .mp4,.rmvb,.mkv
  
  aop:
    proxy-target-class: true
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 180000
      connection-timeout: 1800
      connection-test-query: SELECT 1
    driver-class-name: org.h2.Driver
    #方式一：  引用外部文件
    #url: jdbc:h2:D:/eclipse/xy.db
    #方式二： 引用项目中的文件
    url: jdbc:h2:./test
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    database: H2
    #open-in-view: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
       
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
    mode: HTML5
  main:
    banner-mode: console
    web-application-type: servlet
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true
